[package]
name = "lock_free_cell"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-utils = "0.8.21"
nohash-hasher = "0.2.0"
seize = "0.5.0"


[dev-dependencies]
criterion = "0.6.0"
arcshift = "0.3.1"
arc-swap = "1.7.1"

[[bench]]
name = "bench"
harness = false
